### ISSUE TITLE
License

### ISSUE THREAD

**Issue by PavelSamanek** [erizet/NlogViewer#10]
Hello, 

is this open source project? There is no license specified.

Thank you,

Pavel

**Comment by PavelSamanek** [comment]
I believe it's open source, right? - As multiple developers contribute to the project. I will assume that. If otherwise please contact me. Thank you!

**Comment by erizet** [comment]
Excuse my late reply. It's open source. Use it as you like.

**Comment by erizet** [comment]
I've added a license now.
